[project]
name = "Accuracy_Benchmarking"
version = "0.1.0"
description = "Evaluate the accuracy of a LLM (full + quantized)"
requires-python = ">=3.12"

dependencies = [
    "torch>=2.9.0",
    "transformers>=4.55.2",
    "lm-eval[ifeval]==0.4.9.2"
]
