[project]
name = "Performance_Benchmarking"
version = "0.1.0"
description = "Benchmark system level performance of a LLM using GuideLLM"
requires-python = ">=3.12"

dependencies = [
    "vllm>=0.11.0",
    "openai==2.8.1",
    "guidellm==0.5.0"
]
